name: sharing_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.4.2

  device_info_plus: ^11.3.3
  
  network_info_plus: ^6.1.3

  provider: ^6.1.2

  font_awesome_flutter: ^10.8.0

  marquee: ^2.3.0

  file_picker: ^9.2.2
  path: ^1.9.1
  path_provider: ^2.1.5
  downloadsfolder: ^1.1.0

  http: ^1.3.0

  mime: ^2.0.0

  another_flushbar: ^1.12.30

  flutter_local_notifications: ^19.1.0

  desktop_drop: ^0.6.0

  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  intl: ^0.19.0

  connectivity_plus: ^6.1.4

  flutter_launcher_icons: ^0.14.3

  flutter_localization:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/blitzshare.png
